// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcgyI7bQLTAd1q-IyOh-WrXTLpDHWMLLI',
    appId: '1:799795477803:web:056e52beeb1e43256d996e',
    messagingSenderId: '799795477803',
    projectId: 'student-timetable-app-fec3d',
    authDomain: 'student-timetable-app-fec3d.firebaseapp.com',
    storageBucket: 'student-timetable-app-fec3d.firebasestorage.app',
    measurementId: 'G-8CJQ32V2NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR49SkbvMC2v-Mjan7V62aHVAKFp7rF0E',
    appId: '1:799795477803:android:e9b3e9bf6e2495b46d996e',
    messagingSenderId: '799795477803',
    projectId: 'student-timetable-app-fec3d',
    storageBucket: 'student-timetable-app-fec3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1uP6qv2sQQ8ChEb-VT14A9ZAUx-3UOaM',
    appId: '1:799795477803:ios:0381d472d6ab40696d996e',
    messagingSenderId: '799795477803',
    projectId: 'student-timetable-app-fec3d',
    storageBucket: 'student-timetable-app-fec3d.firebasestorage.app',
    iosBundleId: 'com.example.studentTimetableApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1uP6qv2sQQ8ChEb-VT14A9ZAUx-3UOaM',
    appId: '1:799795477803:ios:0381d472d6ab40696d996e',
    messagingSenderId: '799795477803',
    projectId: 'student-timetable-app-fec3d',
    storageBucket: 'student-timetable-app-fec3d.firebasestorage.app',
    iosBundleId: 'com.example.studentTimetableApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcgyI7bQLTAd1q-IyOh-WrXTLpDHWMLLI',
    appId: '1:799795477803:web:f1809d8b00b03b176d996e',
    messagingSenderId: '799795477803',
    projectId: 'student-timetable-app-fec3d',
    authDomain: 'student-timetable-app-fec3d.firebaseapp.com',
    storageBucket: 'student-timetable-app-fec3d.firebasestorage.app',
    measurementId: 'G-3HH648GDFS',
  );
}
