// Mocks generated by Mockito 5.4.6 from annotations
// in student_timetable_app/test/unit/presentation/viewmodels/subjects_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:student_timetable_app/features/subjects/domain/entities/subject_entity.dart'
    as _i5;
import 'package:student_timetable_app/features/subjects/domain/repositories/subjects_repository.dart'
    as _i2;
import 'package:student_timetable_app/features/subjects/domain/usecases/add_subject_usecase.dart'
    as _i6;
import 'package:student_timetable_app/features/subjects/domain/usecases/delete_subject_usecase.dart'
    as _i8;
import 'package:student_timetable_app/features/subjects/domain/usecases/get_subjects_usecase.dart'
    as _i3;
import 'package:student_timetable_app/features/subjects/domain/usecases/update_subject_usecase.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSubjectsRepository_0 extends _i1.SmartFake
    implements _i2.SubjectsRepository {
  _FakeSubjectsRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetSubjectsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSubjectsUsecase extends _i1.Mock
    implements _i3.GetSubjectsUsecase {
  MockGetSubjectsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SubjectsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeSubjectsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.SubjectsRepository);

  @override
  _i4.Future<List<_i5.SubjectEntity>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.SubjectEntity>>.value(<_i5.SubjectEntity>[]),
      ) as _i4.Future<List<_i5.SubjectEntity>>);
}

/// A class which mocks [AddSubjectUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddSubjectUsecase extends _i1.Mock implements _i6.AddSubjectUsecase {
  MockAddSubjectUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SubjectsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeSubjectsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.SubjectsRepository);

  @override
  _i4.Future<void> call(_i5.SubjectEntity? subject) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [subject],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [UpdateSubjectUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateSubjectUsecase extends _i1.Mock
    implements _i7.UpdateSubjectUsecase {
  MockUpdateSubjectUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SubjectsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeSubjectsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.SubjectsRepository);

  @override
  _i4.Future<void> call(_i5.SubjectEntity? subject) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [subject],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [DeleteSubjectUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteSubjectUsecase extends _i1.Mock
    implements _i8.DeleteSubjectUsecase {
  MockDeleteSubjectUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SubjectsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeSubjectsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.SubjectsRepository);

  @override
  _i4.Future<void> call(String? id) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
